### ISSUE TITLE
New Swift library available

### ISSUE THREAD

**Issue by fitomad** [joakimskoog/AnApiOfIceAndFire#100]
You can find it on [this repository](https://github.com/fitomad/WesterosKit)

**Comment by joakimskoog** [comment]
Nice work! Feel free to create a pull request where you add it to the documentation. :)

**Comment by joakimskoog** [comment]
Fixed in https://github.com/joakimskoog/AnApiOfIceAndFire/commit/a0dd938919d76d1e65a187580dd06a01f23e4a89

**Comment by fitomad** [comment]
Sorry for the delay. It has been a _crazy_ days at work. Thanks for listing ;-)

**Comment by joakimskoog** [comment]
No worries mate, I took care of it. :)
