### ISSUE TITLE
Missing data for Samwell Tarly

### ISSUE THREAD

**Issue by joakimskoog** [joakimskoog/AnApiOfIceAndFire#109]
It seems that Samwell Tarly is missing lots of data such as Books, PlayedBy, TvSeries and more.

**Comment by StevoStabs** [comment]
I just submitted a pull request after filling in Samwell Tarly's info.

**Comment by joakimskoog** [comment]
Thank you for the pull request, great work! I will merge it either later tonight or tomorrow depending on how things pan out.

**Comment by joakimskoog** [comment]
Merged
