### ISSUE TITLE
Using AutoMapper insteading of using Custom IMapper<Source, Destination>

### ISSUE THREAD

**Issue by arunselvakumar** [joakimskoog/AnApiOfIceAndFire#114]
I see the mappers implemented in the project is using IMapper, I feel it would be better if we can implement AutoMapper Library - would be more readable.

Any reasons not been implemented yet?

**Comment by joakimskoog** [comment]
Hello Arun,

When I wrote the code I just wanted to be done with it quickly, hence rolling my own mapper. If you think that using AutoMapper would be better and more readable you're welcome to implement it and send a pull request. :)

**Comment by arunselvakumar** [comment]
Cool man :)

**Comment by joakimskoog** [comment]
This will probably be implemented in the upgrade to .NET Core

**Comment by arunselvakumar** [comment]
Can I be a part of ASP.NET Core Migration, are you planning to start that in a separate repo?

**Comment by joakimskoog** [comment]
@arunselvakumar: You sure can, although I prefer to wait until ASP.NET Core 2.0 is out of preview.

**Comment by arunselvakumar** [comment]
@joakimskoog I am waiting :-)

**Comment by joakimskoog** [comment]
Manually mapping is faster, will revisit this issue if anyone find any data on AutoMapper being faster. AutoMapper might be a bit easier to read but I prefer speed over readability, at least in mapping scenarios.
