### ISSUE TITLE
Add Coat of Arms for Houses

### ISSUE THREAD

**Issue by RNOVOSELOV** [joakimskoog/AnApiOfIceAndFire#118]
It would be nice if you add URL to the image of the coat of arms for the houses

**Comment by joakimskoog** [comment]
Refer to my answer on the following issue since it relates to this one.
https://github.com/joakimskoog/AnApiOfIceAndFire/issues/119

**Comment by joakimskoog** [comment]
I'm merging all discussions about images in this issue: https://github.com/joakimskoog/AnApiOfIceAndFire/issues/127
