### ISSUE TITLE
Placeholder example data on anapioficeandfire.com is outdated

### ISSUE THREAD

**Issue by chasebank** [joakimskoog/AnApiOfIceAndFire#122]
The initial Jon Snow character data is outdated. If you do a real search or click the hint link, the result is updated to correct info, but it looks like the initial example is hard coded. This is actually important for first impressions, because tvSeries only listed him through Season 5, which made me incorrectly assume this entire API is outdated.

I'm assuming https://github.com/joakimskoog/AnApiOfIceAndFire/blob/master/AnApiOfIceAndFire/Views/Home/Index.cshtml is the target file?

I was going to just update the hard coded example, but then it still isn't future proof. Is there any concern with adding something like this to the bottom of that page's js?
```
window.onload = updateRequestUrl('characters/583');
```

**Comment by joakimskoog** [comment]
The reason the data is hard coded is that I didn't want to add an extra request for all users. Although I think everyone would prefer updated data over a miniscule slow down of the site.

No, there shouldn't be any problem to add that. You're welcome to make a pull request with that change.

**Comment by joakimskoog** [comment]
Fixed in https://github.com/joakimskoog/AnApiOfIceAndFire/tree/aspnetcore11-port
