### ISSUE TITLE
Any interest in images?

### ISSUE THREAD

**Issue by joakimskoog** [joakimskoog/AnApiOfIceAndFire#127]
We've gotten a few issues where people are asking about images of characters but also houses. Would this be something that you guys would be interested in? This will be the main issue about discussing images, all other issues will be closed and referred to this one until we've decided what to do.

**Pros**
- We add a new dimension to the API, people love to see what the characters look like and also what coat of arms the houses have.

**Cons**
- Expensive to host our own images
- Will take a lot of work on getting images in the same style and with a correct license

**Previous discussions**
- https://github.com/joakimskoog/AnApiOfIceAndFire/issues/119
- https://github.com/joakimskoog/AnApiOfIceAndFire/issues/118

**Comment by jbehrens94** [comment]
Suggestion: you could just serve base64 strings instead of image URLs and such.

**Comment by joakimskoog** [comment]
@jbehrens94: What would the advantage be?

**Comment by AllanOcelot** [comment]
There would be no difference file size wise, I'd say leave images up to the user. We'll have a big issue with copyright if we host images and as stated above, cost. 

If users wanted to display images (of a character for example) they could always do 'background-image:url(/assets/images/characters/id12345.png' ) on their end using the API to get said ID.

**Comment by joakimskoog** [comment]
Closed. Feel free to open a new issue if this is still interesting.
