### ISSUE TITLE
Proposition: Better structured date format

### ISSUE THREAD

**Issue by joakimskoog** [joakimskoog/AnApiOfIceAndFire#133]
**Problem:** The way dates are handled make a bunch of fields kind of useless. An example is the `Born-` and `Died`-fields which are populated with data that looks like this:

- `In 249 AC` 
- `In or between 253 AC and 272 AC`

This makes querying against these fields near impossible. 

**Suggested solution:**
Introduce a new format for dates, which would look something like this:

```csharp
public enum Era
{
    BeforeConquest = 0,
    AfterConquest = 1
}

public class Date
{
    public Era Era { get; set; }
    public int Year { get; set; }
}
```

This would enhance the querying capabilities and and also enable us to check for ranges. 
Example: `Get me all characters that were born between 10 AC and 30 AC`

**Comment by ghost** [comment]
We are doing some work on Graph Databases here at the moment, looking at your data set (wow what a lot of data!), this would potentially be ideal represented as a Graph Database.

**Comment by joakimskoog** [comment]
I'm not interested in converting the whole thing to a graph database but you're more than welcome to start a project like that. :)
