### ISSUE TITLE
AngujarJS $http response - Link Header

### ISSUE THREAD

**Issue by avinashpandeshwar** [joakimskoog/AnApiOfIceAndFire#134]
Hello there, I cant seem to get the Link header for $http GET response. Looks like this may be a CORS issue.
Can you kindly let me know if "Access-Control-Expose-Headers" includes "Link"?

Ref: [https://stackoverflow.com/questions/37400091/missing-headers-in-response-for-jquery-request-with-cors](url)

**Comment by joakimskoog** [comment]
Hmmm, I thought that the code below was enough:

` app.UseCors(cors =>
{
                cors.AllowAnyOrigin().AllowAnyHeader().WithMethods("GET", "HEAD");
});`

It seems like that we need to use [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) and add `Link` to it.

**Comment by joakimskoog** [comment]
@avinashpandeshwar This issue was fixed in https://github.com/joakimskoog/AnApiOfIceAndFire/commit/ae8a6f6798ee5957b4e89ccb15ae042f9e9d37ac

Please create a new issue if the problem persists.

**Comment by avinashpandeshwar** [comment]
Fixed. Thanks.
