### ISSUE TITLE
Directly pull data from the Wiki of Ice and Fire

### ISSUE THREAD

**Issue by napsternxg** [joakimskoog/AnApiOfIceAndFire#136]
In line with adding more fine grained information, I think it would be a great addition to pull data from http://awoiaf.westeros.org and write a data scraper to do so. The data itself is available under  CC-BY-SA license. If we can ask the community to generate monthly dumps of the Wiki Articles XML like Wikipedia does, then loading data from it into this API would be very easy. 

This will require some collaboration with people at the awoiaf but can be a wonderful contribution to the ASoIaF community.

**Comment by napsternxg** [comment]
More details on how to create dumps from Media Wiki are at https://www.mediawiki.org/wiki/Help:Export

**Comment by napsternxg** [comment]
OK I was able to download the data from the Wiki for each chapter and just need to parse it to convert it into a structured format. The code is here https://github.com/napsternxg/AWoIaF-Data

If you want to contribute to this and see how this can fit in, it would be great.

**Comment by joakimskoog** [comment]
This might be useful. What type of data are you referring to when you write: 

> more fine grained information

?

**Comment by joakimskoog** [comment]
Closed. Please open a new issue if this is still needed.
