### ISSUE TITLE
Incomplete URLs for some objects

### ISSUE THREAD

**Issue by avinashpandeshwar** [joakimskoog/AnApiOfIceAndFire#137]
Have noticed this for some objects...that based on the URL used for GET request, the data is incomplete.

Below pseudo code should explain.
```
book = GET(https://www.anapioficeandfire.com/api/books)
book[0].characters //contains incomplete URLs
/*
Example:
    "characters": [
        "http:///api/characters/2",
        "http:///api/characters/12",
        "http:///api/characters/13",
        "http:///api/characters/16",
        "http:///api/characters/20",
        .
        .
        .
*/
```

```
book = GET(https://www.anapioficeandfire.com/api/books/2)
book.characters //is fine
/*
Example:
        "characters": [
            "https://www.anapioficeandfire.com/api/characters/2",
            "https://www.anapioficeandfire.com/api/characters/12",
            "https://www.anapioficeandfire.com/api/characters/13",
            "https://www.anapioficeandfire.com/api/characters/16",
            "https://www.anapioficeandfire.com/api/characters/20",
            .
            .
            .
*/
```

**Comment by joakimskoog** [comment]
I've looked at this and this is what I've come up with so far:

**What we know so far:**

- All single endpoints are affected (`/api/books/{id}`, `/api/characters/{id]` and `/api/houses/{id}`
- It does not happen on every request
- When the error occurs **only** URLs in arrays are wrong, not the ones in the simple properties.

**Request:** `https://www.anapioficeandfire.com/api/houses/229`
**Response:** 

```
...
 "currentLord": "https://www.anapioficeandfire.com/api/characters/238",
    "heir": "",
    "overlord": "https://www.anapioficeandfire.com/api/houses/16",
    "founded": "Age of Heroes",
    "founder": "https://www.anapioficeandfire.com/api/characters/615",
    "diedOut": "",
    "ancestralWeapons": [
        "Brightroar"
    ],
    "cadetBranches": [
        "http:///api/houses/228",
        "http:///api/houses/230",
        "http:///api/houses/231",
        "http:///api/houses/232",
        "http:///api/houses/233"
    ],
...
```

**Comment by avinashpandeshwar** [comment]
Oops..my bad. I pasted the example in reverse. You are right. For a single book, we are seeing this issue.

**Comment by joakimskoog** [comment]
I'm wondering if it has something to do with the properties being `IEnumerable`. I'm suspecting that they get resolved too late in the pipeline, seeing as they are lazy loaded, where we don't have access to the host name  of the given request.

I'll change them to be regular arrays and let you know when I've pushed the change, hopefully it will fix the problem.

**Comment by joakimskoog** [comment]
@avinashpandeshwar: The [fix](https://github.com/joakimskoog/AnApiOfIceAndFire/commit/fb13a2414598535cc76d3daaa9095aeb55e4308b) is live now and I can't seem to reproduce the error anymore. Can you try and see if the problem still persists or if it's fixed?

**Comment by avinashpandeshwar** [comment]
I don't see the issue any more. Thanks for the fix.
