### ISSUE TITLE
here are all the other datasets you can add

### ISSUE THREAD

**Issue by swyxio** [joakimskoog/AnApiOfIceAndFire#139]
hi! i did some pulling together for you. i dont know csharp so i cant contribute to your project but think it will be trivial foryou to include this data. at minimum include the kaggle data!

---

- [Jeffrey Lancaster's all the things](https://github.com/jeffreylancaster/game-of-thrones) - [Writeup here](https://medium.com/@jeffrey.lancaster/the-ultimate-game-of-thrones-dataset-a100c0cf35fb) This thing is a fucking masterpiece - [Sankey diagram!!!](https://jeffreylancaster.github.io/game-of-thrones/) and has like 20 views. i want to buy shares in it.
- [neo4j data scrape from wikia/wikipedia](https://github.com/mneedham/neo4j-got/tree/master/data)
- [books data for network analysis](https://github.com/mathbeveridge/asoiaf) - blog [here](https://networkofthrones.wordpress.com/)
- [AoIaF Data cleaned by IBM](https://developer.ibm.com/clouddataservices/wp-content/uploads/sites/47/2016/04/gameofthrones_scrubbed-gameofthrones-004.txt)/[and here](https://developer.ibm.com/clouddataservices/wp-content/uploads/sites/47/2016/04/gameofthrones.txt) - writeup [here](https://developer.ibm.com/clouddataservices/2016/04/19/winter-is-coming-importing-game-of-thrones-data-into-cloudant-with-the-simple-search-service/)
- [AFFC Share Copy](https://docs.google.com/spreadsheets/d/1gEZUEo8GUP5b6Tup6wzUG90erpDPgOyGhbB5GfMrk7E) Character database, no family relationships only house relationships
- [OrientDB scrape of the Wikia](http://gog.orientdb.com/index.html#/download) - has a ton of relations which is great, but in a proprietary db format
- [GOT Transcripts](https://gameofthronesscripts.wordpress.com/) - what it says on the tin. dead simple. 
- [Season Recaps](https://duelingdata.blogspot.com/2017/07/game-of-thrones-season-6-recap.html) - number of lines in season 6 by character . Here are [show appearances over 5 seasons](https://duelingdata.blogspot.com/2016/04/game-of-thrones-analysis.html)
- [Character Data](https://github.com/girikuncoro/thrones) scraped from wikia up to season 5. may have usable python code
- [Screentime Data](https://data.world/aendrew/game-of-thrones-screen-times) from [IMDB](http://www.imdb.com/list/ls076752033/)
- [Battles, deaths, death predictions](https://www.kaggle.com/mylesoneill/game-of-thrones/data) only battle dataset available. some [handy Python crunching of this data explained here](https://datascienceplus.com/network-analysis-of-game-of-thrones/) and more [usage](http://justingosses.com/game-of-thrones-parallel-sets-data-visualization/) [here](http://justingosses.com/ParaSet_Oct2/) and [here](https://tbgraph.wordpress.com/2017/06/24/neo4j-game-of-thrones-part-1/)
- [Deaths](https://data.world/aendrew/game-of-thrones-deaths) - source from [Time](http://time.com/3924852/every-game-of-throne/)
- [Episode data](https://en.wikipedia.org/wiki/List_of_Game_of_Thrones_episodes) from wikipedia
- [Character Data in excel](https://trumpexcel.com/game-of-thrones-dashboard/) with screentime and status and actor and episode rating
- [Betrayals](https://docs.google.com/spreadsheets/d/1yfzwRZFY08EBgwfMYTY8BojB4GIfsOBLo0PQ2Hs8u5g/edit#gid=0) from [venngage](https://venngage.com/blog/game-of-thrones-infographic/)

**Comment by joakimskoog** [comment]
What a nice contribution, great job! Which one of these do you think would be the most valuable to the API?

**Comment by swyxio** [comment]
no idea. i think the kaggle datasets are useful and popular

**Comment by joakimskoog** [comment]
Closed for now. Please open a new issue if it's still interesting.
