### ISSUE TITLE
Add a global.json

### ISSUE THREAD

**Issue by jbehrens94** [joakimskoog/AnApiOfIceAndFire#140]
The repository should include a global.json in order to fix the .NET Core version the project was developed on. Now, the project will currently target the latest version currently installed on the machine, that will vary for everyone.

**Comment by joakimskoog** [comment]
Good idea, hadn't even thought about that!

**Comment by joakimskoog** [comment]
Added in https://github.com/joakimskoog/AnApiOfIceAndFire/commit/7ce73f88f7534f7c80c3d931281644df6d42c96c
