### ISSUE TITLE
Searching characters by name

### ISSUE THREAD

**Issue by KBPsystem777** [joakimskoog/AnApiOfIceAndFire#142]
Hi, how would I implement a specific character search for this API? Like for example:

[https://anapioficeandfire.com/api/characters/name="Arya%Stark"](https://anapioficeandfire.com/api/characters/name="Arya%Stark")

after running this url, I am receiving `400 Bad Request`

appreciate your help. Thanks

**Comment by joakimskoog** [comment]
https://anapioficeandfire.com/Documentation#characters
> Filtering characters
> You can also include filter parameters in your request to the characters endpoint by including parameters in the query string.

Which means that you should use the query strings like so:
`https://anapioficeandfire.com/api/characters?name=Arya%20Stark`
