### ISSUE TITLE
Api with Graphql

### ISSUE THREAD

**Issue by patrick-souza** [joakimskoog/AnApiOfIceAndFire#143]
Estou tentando realizar chamadas do frontend com graphql. a api está pronta para receber os parâmetros ?

**Comment by joakimskoog** [comment]
Could you please post in english instead? I'm just guessing by your title that you want support for GraphQL as well? I don't have any plans on adding support for it but since the data is open source and free to use I don't see any problems with anyone else creating a GraphQL API for it.
