### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by AO19** [joakimskoog/AnApiOfIceAndFire#178]
In the documentation on the website, the url is missing a letter.

```
Get specific house
$ curl "https://www.anapioficeandfire.co/api/houses/10"
Example response:
```

Should be .com not .co

Found this typo, because I just copied this text to test it.

**Comment by joakimskoog** [comment]
Fixed in https://github.com/joakimskoog/AnApiOfIceAndFire/commit/a5163d1716802fcb2cff9c6df5a490bef61ba604. Thanks for reporting it!
