### ISSUE TITLE
List all houses only returns 9 houses

### ISSUE THREAD

**Issue by AO19** [joakimskoog/AnApiOfIceAndFire#179]
In the documentation it says:
```
List all houses:
$ curl "https://www.anapioficeandfire.com/api/houses"
Example response:
```
But I only get 9 results back. When I use the pagination api, I get about 100+.

Is this the correct behavior?

**Comment by blacksector** [comment]
From their documentation it states under the Pagination section: `To prevent our servers from getting cranky, the API will automatically paginate the responses.`

So I believe that is the intended behaviour.

**Comment by joakimskoog** [comment]
Yeah, @blacksector is correct. Returning hundreds of houses each time would cause unnecessary load
