### ISSUE TITLE
Can't reach the api

### ISSUE THREAD

**Issue by Manu1909** [joakimskoog/AnApiOfIceAndFire#194]
Currently I'm not able to reach the api.
Following error message appears:

"Response:

Somethin went wrong. If this keeps happening, please post an issue at: https://github.com/joakimskoog/AnApiOfIceAndFire/issues"

**Comment by ZBarrington** [comment]
Same here!

**Comment by jacquibushfi** [comment]
Same here.  Also getting the CORS issue earlier

**Comment by joakimskoog** [comment]
Thanks for letting me know! I had some trouble with my hosting provider. Restarted the application which seemed to solve the problem. Is it working for you guys now?

**Comment by Manu1909** [comment]
Works fine now! Thank you for your help :)
