### ISSUE TITLE
"All houses"- api-call only lists the first 10 houses

### ISSUE THREAD

**Issue by Manu1909** [joakimskoog/AnApiOfIceAndFire#195]
Hi there, 
when I'm calling the API for all houses I only get the first ten houses as a response.
Is this a normal behavior or is the some issue in the implementation?

Thanks for your time.

Best regards

**Comment by joakimskoog** [comment]
That's normal behavior, please refer to https://anapioficeandfire.com/Documentation#pagination for more information. 😊

**Comment by Manu1909** [comment]
Thank you very much.
