### ISSUE TITLE
CSS on Api Homepage

### ISSUE THREAD

**Issue by constbeecoding** [joakimskoog/AnApiOfIceAndFire#244]
I can fix :) Just found it during a course using this API.

Issue: Text pushes outside of the <div class="row" id="get-involved"> and it's children. Seems to affect CSS for the Tablet Viewport and Laptop Viewports.

Tablet:
![Screenshot 2023-09-02 at 1 52 51 PM](https://github.com/joakimskoog/AnApiOfIceAndFire/assets/63125095/a059816b-9fa7-41b6-b41d-0311bd71a937)

Laptop at 1024 viewport Width:
![Screenshot 2023-09-02 at 1 52 45 PM](https://github.com/joakimskoog/AnApiOfIceAndFire/assets/63125095/a1a3c165-61f8-41d5-a82f-a2b5ea4097ed)

**Comment by joakimskoog** [comment]
Nice find! I've redesigned the UI now so this shouldnt be an issue anymore :)
