### ISSUE TITLE
Circular suzerain><vassal

### ISSUE THREAD

**Issue by tapioca-design** [joakimskoog/AnApiOfIceAndFire#265]
It seems a circular loop and not consistant to me that : 
https://anapioficeandfire.com/api/houses/15
has overlord 16
and 
https://anapioficeandfire.com/api/houses/16
has overlord 15

One can't be boss of its boss...
Am I wrong ? thx, Sylvain.

**Comment by joakimskoog** [comment]
Yeah that looks like a bug in the data. House 16 shouldn't have any overlord, right?

**Comment by tapioca-design** [comment]
Guess so yeah. The amout of work is so huge ! Did you build those data manually ?

**Comment by joakimskoog** [comment]
A bit of manual work was required to clean up the data but otherwise it was collected automatically
