### ISSUE TITLE
Add rust library to wiki?

### ISSUE THREAD

**Issue by Yag000** [joakimskoog/AnApiOfIceAndFire#271]
I've been working on a Rust library for this API and noticed that there are some libraries mentioned in the wiki. Would it make sense to add mine as well?

Here's the repo: [asoiaf-rs](https://github.com/Yag000/asoiaf-rs).

**Comment by joakimskoog** [comment]
Sure! All libraries are welcome, just create a PR and I'll merge it :)

**Comment by Yag000** [comment]
I'd gladly do it, but from what I understand, that part of the website has been moved to a GitHub wiki, which I don't think I can make a PR to. It might be possible, but I haven't found a way to do it yet.

**Comment by joakimskoog** [comment]
Oh yeah, I totally forgot about that. Sorry! Adding it now :)

**Comment by Yag000** [comment]
Thanks !
