### ISSUE TITLE
403 Forbidden Responses on Python urllib.request.urlopen calls

### ISSUE THREAD

**Issue by mohanbharath** [joakimskoog/AnApiOfIceAndFire#46]
Accessing any portion of [the API](https://anapioficeandfire.com/) through the urlopen function of Python 3's [urllib.request](https://docs.python.org/3.0/library/urllib.request.html) library results in a 403 code being returned. This includes even the main homepage, not just calls to the API. However, access through the browser seems to work as intended, as I'm able to access JSON data directly by entering resource URLs into the navigation bar (at least, on Chrome).

**Comment by joakimskoog** [comment]
Hello,

Have you tried setting an user-agent? That might be the reason it works in Chrome but not in your code.

**Comment by mohanbharath** [comment]
Hello,

Python's urllib does have a default user-agent of 'Python-urlllib/{version_number}', where {version_number} is replaced by the version of python being used. Is there any reason this should be changed, especially considering that your API will presumably largely be used by automated services as opposed to browsers? Or are you simply suggesting I use some other user-agent name, not necessarily that of a browser?

**Comment by mohanbharath** [comment]
An update - spoofing the user-agent as a browser does work; in fact, replacing it with anything (including 'App/1.4') seems to work, so I suppose this is, in a way, resolved.

**Comment by joakimskoog** [comment]
Awesome, I'm glad it works now. I'm closing this since it seems to be resolved.
