### ISSUE TITLE
Remove keys with empty (null, []) values from datafiles.

### ISSUE THREAD

**Issue by jsenko** [joakimskoog/AnApiOfIceAndFire#49]
If the schema is defined, replacing

```
{"Id":38,"Name":"Aegon I","Culture":"","Titles":["King of All Westeros","Shield of His People","King of the Andals, the Rhoynar and the First Men","Lord of the Seven Kingdoms","Protector of the Realm","Lord of Dragonstone"],"Aliases":["Aegon the Conqueror","Aegon the Dragon","Aegon the Dragonlord"],"Born":"27 BC, at Dragonstone","Died":"37 AC, at Dragonstone","Father":59,"Mother":1070,"Spouse":2071,"Children":[57,694],"Allegiances":[],"Books":[11,9,4,6,7,1,2,3,5,8],"PovBooks":[],"PlayedBy":[""],"TvSeries":[]}
```

with

```
{"Id":38,"Name":"Aegon I","Titles":["King of All Westeros","Shield of His People","King of the Andals, the Rhoynar and the First Men","Lord of the Seven Kingdoms","Protector of the Realm","Lord of Dragonstone"],"Aliases":["Aegon the Conqueror","Aegon the Dragon","Aegon the Dragonlord"],"Born":"27 BC, at Dragonstone","Died":"37 AC, at Dragonstone","Father":59,"Mother":1070,"Spouse":2071,"Children":[57,694],"Books":[11,9,4,6,7,1,2,3,5,8]}
```

will save significant space.

**Comment by mohanbharath** [comment]
Wouldn't consistency over conciseness be more appropriate here, since an empty list is more representative? For something like missing culture, it could simply be replaced with "unknown," but empty lists seems to be a good idea in order to keep consistency.

Just my 2 cents, though.

**Comment by jsenko** [comment]
Oh, I meant do this only in the dataset files, not necessarily in the returned JSON.

**Comment by mohanbharath** [comment]
Ah, gotcha. That seems like a fairly good suggestion, then.

**Comment by joakimskoog** [comment]
I don't think space is anything to worry about. I think it's more important to be consistent so that it's easier to, for example, add an id to the `povBooks` array instead of creating the array in the "correct" place and then adding the ID.
