### ISSUE TITLE
Adding data via pull-requests is not sustainable.

### ISSUE THREAD

**Issue by jsenko** [joakimskoog/AnApiOfIceAndFire#50]
Users should be allowed to suggest new data/corrections directly (via API). System could track these suggestions separately in the server DB, and the changes could be reviewed by people and saved to the dataset files in a batch.

**Comment by joakimskoog** [comment]
I'm hesitant to add this since that means we must add some sort of authorization to prevent malicious users. It might reconsider if this is sought after by the users.

**Comment by hyperfocusr** [comment]
Came here to suggest this too - I have noticed some errors in the characters.json data - some of which are carried across from the wiki. (e.g. Biter has an Alias listed: "Biter by Amok©")
