### ISSUE TITLE
Add filtering on entity fields (equals, contains (for lists), and, like)

### ISSUE THREAD

**Issue by jsenko** [joakimskoog/AnApiOfIceAndFire#52]
There is probably some library for that. I see a possible problem if the foreign keys are "expanded" in the JSON. Maybe do the expansion only on request?

**Comment by joakimskoog** [comment]
It would be nice to have filtering, this would provide lots of functionality such as only retrieving all **northern**, example: `houses: /api/houses?culture=northmen`. Do you have any other suggestions on what people would like to filter on? All the fields?
