### ISSUE TITLE
Python wrapper, can be added to Documentation

### ISSUE THREAD

**Issue by mohanbharath** [joakimskoog/AnApiOfIceAndFire#53]
Hello, 

I posted a comment on your reddit post as well, and here's the promised issue for your closer look:

I've implemented an [extremely basic Python wrapper](https://github.com/mohanbharath/python-wrapper-aaoiaf) as requested. As far as features, this simply takes the given information and packages them into classes for easy use in applications, and also provides a few methods for auto-generation of objects as well from resource URLs (getting spouse/father/mother objects from the resource URLs given). If there's something else you'd like to see implemented, please let me know and I'll look into getting it done ASAP

A suggestion I'd have is perhaps looking into the data contained by the [AGOT mod for Crusader Kings II](http://citadel.prophpbb.com/forum3.html), which has a lot of character data for a lot of characters in Westeros - ancestry, sentences, birth dates, death dates. I don't know how much of this is perfectly accurate, canon information, but definitely some of it would be, while others are probably extrapolated. 

Also, one other thing I might suggest is adding a "children" field array and a "siblings" field array for easy family tree navigation - the current method only allows traveling up the family tree, not back down or sideways. 

Let me know if I can help in any way, or if you need clarification, or really anything!

**Comment by joakimskoog** [comment]
This is basically just the models. I won't add it **as is** because it does not help people make calls to the API at the moment. Take a look at the other libraries and see how they've done.

**Comment by joakimskoog** [comment]
Closing this for now, please add a pull request when the library meets the expectations I wrote about in the comment above.
