### ISSUE TITLE
Time/chapter-based data

### ISSUE THREAD

**Issue by abaddon82** [joakimskoog/AnApiOfIceAndFire#55]
The way the data is structured now, all the values are set to what they are at the end of the last book. Imagine if we could have a timeline of some sort, that way we could request stuff at different times in the story. Examples:
- Where is Dany when Eddard is beheaded?
- Who is Master of Ships as of AFFC?
- How and when did Tywin's titles change?

This would of course require a pretty massive rewrite of both the data and its management. Anyway, just food for thought :)

**Comment by joakimskoog** [comment]
This would actually be really interesting, just imagine everything you could do! It's a pretty big re-write though and it would take quite some long time to add the data. I'll mark it as version 2 and if anyone is interested they can go ahead and try it out.

**Comment by joakimskoog** [comment]
This will be too much work. Feel free to open a new issue if this is still interesting.
