### ISSUE TITLE
Sorting of results

### ISSUE THREAD

**Issue by joakimskoog** [joakimskoog/AnApiOfIceAndFire#56]
It would be nice to be able to have the entities in the result sorted by some arbitrary field. Maybe I want to retrieve all houses sorted by region, I would then do something like:
`/api/houses?sort=region`

**Comment by Drtikul** [comment]
Hello, 
I am thinking about contributing to this project and this issue sounds like a interesting thing to do. 

Do you mind if I try it? It would be my first experience with open source development :)

**Comment by joakimskoog** [comment]
Hi,

You're definitely welcome to try anything! Just one note: I would like it to be structured in the same way as the filtering is done. If you have any questions, feel free to ask them.

Also: I'm not sure which values should be sortable but you're welcome to try any of them. :)

**Comment by Drtikul** [comment]
Thank you, I'm gonna read and understand the existing code first, for sure. I will get in touch with you if I would need any information.

**Comment by joakimskoog** [comment]
This sorting can be done on the client side. If people really want this they can open a feature requests but I'm closing it for now.
