### ISSUE TITLE
'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by Paulooze** [joakimskoog/AnApiOfIceAndFire#57]
I tried a simple API call from javascript (front end stuff) and I had an issue with 'Access-Control-Allow-Origin'. I know there are ways to overcome this issue in development, but it would not work in production. Would it be possible to do something about it?

Thank you in advance.

**Comment by joakimskoog** [comment]
CORS is not enabled by default in Web API. I'm not sure that we want to allow it for **all** other sites. I also don't think it's _that_ feasible to add exceptions for a bunch of sites.

Maybe someone else has some thoughts on how this can be done in a feasible way without compromising security?

**Comment by Paulooze** [comment]
Well, it's ok for me - I can make a simple backend that would resend calls from my frontend to your api (thats the simplest way of overcoming this issue in my opinion). Thank you for your answer.

**Comment by joakimskoog** [comment]
Alright, as long as it works for you. I'll close this issue for now.
