### ISSUE TITLE
Consider graph database.

### ISSUE THREAD

**Issue by jsenko** [joakimskoog/AnApiOfIceAndFire#59]
I think that the more complicated and useful questions (relationships, based on history, location, who is the first common ancestor between two characters) could be more easily solved if the data were stored in a graph database.

My favorite is Neo4j (albeit written in Java) which stores data as nodes and edges, each having a type (label) and a variable set of key value properties. There is a query language designed to answer exactly "Who is the common ancestor of Dany and Stannis that he himself is a descendant of Aegon I" type questions (in a single query).

Something to consider given the complexity of relationships in the domain model will only increase.

**Comment by cjduncana** [comment]
How do we get this started?

**Comment by joakimskoog** [comment]
@cjduncana: This is not something that will be implemented in the near future, but as jsenko says, it might be worth considering if we get more complex relationships between our entities.

I've never played around with graph databases but you're welcome to try it out and see how it works.

**Comment by cjduncana** [comment]
@joakimskoog I'll keep y'all posted.

**Comment by cjduncana** [comment]
I have a basic API made with NEO4J and a Flask application at https://github.com/cjduncana/An-API-of-Ice-and-Fire
