### ISSUE TITLE
GraphQL Wrapper avaialable

### ISSUE THREAD

**Issue by afram** [joakimskoog/AnApiOfIceAndFire#73]
I put together a GraphQL wrapper of this API as a way to learn GraphQL :-)

https://github.com/afram/iceandfire-graphql

**Comment by joakimskoog** [comment]
This is awesome! I'll play around a bit with it and then merge your pull request. Thank you for your contribution! :)

**Comment by joakimskoog** [comment]
Merged in 12202ea6d228138be283000522c62934d0109d3f
Good job!
