### ISSUE TITLE
Please enable JSONP

### ISSUE THREAD

**Issue by divmgl** [joakimskoog/AnApiOfIceAndFire#89]
Because we are unable to do cross domain requests, JSONP is a great alternative.

``` C#
var config = GlobalConfiguration.Configuration;
config.Formatters.Insert(0, new JsonpMediaTypeFormatter());
```

**Comment by joakimskoog** [comment]
Good suggestion, but I actually prefer CORS over JSONP. Seeing as we don't have any sensitive user info or data, wouldn't it be safe to enable CORS for all domains?

**Comment by divmgl** [comment]
CORS requests would technically be safe but this is a good alternative for `GET` requests.

**Comment by joakimskoog** [comment]
Which alternative is the easiest one for consumers?

**Comment by divmgl** [comment]
Allowing CORS. You'll need to allow GET requests and `*` on the domain header. Don't remember how to do that in Web API 2.

**Comment by joakimskoog** [comment]
I think that the following would do the trick:
`config.EnableCors(new EnableCorsAttribute("*","*","GET,HEAD"));` 

Note: The Microsoft.AspNet.Cors NuGet package is required.

**Comment by divmgl** [comment]
@joakimskoog Awesome; didn't realize it would be that simple. I appreciate your help.

**Comment by joakimskoog** [comment]
@divmgl Yeah, those things are really simple in Web API 2. You're welcome to make a pull request with that functionality, otherwise I'll be able to fix it later today. :)

**Comment by joakimskoog** [comment]
I took the liberty to enable CORS instead, you should now be able to play around in JS.
Commit: 85f12be88cd0d2e09bd7ac585ffcdd6e101ad10c

**Comment by divmgl** [comment]
Thanks @joakimskoog I don't have a Windows machine, much appreciated

**Comment by joakimskoog** [comment]
@divmgl No worries mate, hope it works!
