### ISSUE TITLE
Filter characters by House

### ISSUE THREAD

**Issue by fitomad** [joakimskoog/AnApiOfIceAndFire#90]
Obtain all `Characters` that serves to a determinate `House`

Something like...

http://www.anapioficeandfire.com/api/characters?house=Stark

**Comment by joakimskoog** [comment]
It's possible to retrieve all `Characters` that are sworn to a `House` by going through the `Houses` endpoint but it might be a good idea to include this as a possibility in the CharacterFilter.

**Comment by joakimskoog** [comment]
Marking this as "Won't fix" since it's, as previously mentioned, possible to retrieve characters sworn to a `House` by going through the houses endpoint. Might add it to version 2 if it's heavily requested.
