### ISSUE TITLE
I made a javascript wrapper for the API.

### ISSUE THREAD

**Issue by arbazsiddiqui** [joakimskoog/AnApiOfIceAndFire#94]
I made a [javascript wrapper](https://github.com/arbazsiddiqui/A-song-of-ice-and-fire-API) for the API.
It contains all the the major filtering and functions to return random things.

**Comment by joakimskoog** [comment]
Awesome work! You're welcome to make a pull requests with your wrapper added to the documentation. :+1:

**Comment by arbazsiddiqui** [comment]
Done. :+1:
